### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rdbende** [rdbende/tkinter-docs#6]
# UI

- [ ] Create chapter navigation for tutorials and docs pages
- [ ] Make better footer

# Code
- [ ] cleanup css, and switch to sass

# Tutorials
(just came to my mind)

- [ ] Make grid tutorial
- [ ] Make pack tutorial
- [ ] Make place tutorial
- [ ] Make vsapi tutorial
- [ ] Make text widget tutorial (because it's awesome imo)
- [ ] someone asked me to make a tutorial on making ttk themes. why not?

**Comment by Akuli** [comment]
We could take the grid/pack/place tutorial from my tkinter-tutorial repo: https://github.com/Akuli/tkinter-tutorial/blob/master/geometry-managers.md

**Comment by rdbende** [comment]
Thanks! It's a very good and understandable source for it. I really like that it shows in which situation which gm is useful because tbh a lot of people don’t use anything else than pack.

Relaxing, and relying, XDD I love it, though I often read them so.

**Comment by Moosems** [comment]
@rdbende I'm wondering if instead of using `href="#"` for the main docs if instead I should make individual pages to elaborate on each item

**Comment by Moosems** [comment]
>  someone asked me to make a tutorial on making ttk themes. why not?

I could actually use that myself.... 😶
